name: Build APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Get Date
        id: get-date
        run: |
          echo "date=$$(date +'%Y-%m-%d')" >> $$GITHUB_OUTPUT

      - name: Cache Buildozer
        uses: actions/cache@v4
        with:
          path: .buildozer
          key: $${{ runner.os }}-buildozer-$${{ hashFiles('buildozer.spec') }}-${{ steps.get-date.outputs.date }}

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          buildozer_version: master
          command: buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: enzo_app_debug
          path: bin/*.apk
